### ISSUE TITLE
新婚さんクイズのアプリ作成前にやっておくこと

### ISSUE THREAD

**Issue by shinmura326** [mantaroh/okamura#10]
４択クイズ
- [x]  クイズ面白いやり方を考える（３０分）
- [x]  サンプル問題の回答を考える
- [x]  追加問題案を１０問考えたい
```
・新郎新婦の入籍日は次のうちどれ？
・二人はお互いに何と呼び合っているでしょうか？
・プロポーズの言葉・場所は次のうちどれ？
・新郎の普段の行動で新婦が気になっているところは？
・入籍日を○月×日にした理由は次のうちどれ？
・次のうち、新婦が実際にやってしまった失敗はどれ？
・新郎新婦が一番最初に出会った場所は次のうちどれ？
・初デートの場所は次のうちどれ？
・今まで新婦が一番嬉しかった新郎の言葉はどれ？
・新郎の得意なモノマネはなんでしょう？
  (実際に新郎にやってもらう)
```

**Comment by okamuran** [comment]
・新郎新婦の入籍日は次のうちどれ？
　→7月17日
・二人はお互いに何と呼び合っているでしょうか？
　→新郎：ちさっちゃん　新婦：むーちゃん
・プロポーズの言葉・場所は次のうちどれ？
　→酔っ払って覚えていない
・新郎の普段の行動で新婦が気になっているところは？
　→飲み過ぎ？
・入籍日を○月×日にした理由は次のうちどれ？
　→天赦日
・次のうち、新婦が実際にやってしまった失敗はどれ？
　→２人のLINEのやり取りを全部消す
・新郎新婦が一番最初に出会った場所は次のうちどれ？
　→新宿の飲み屋
・初デートの場所は次のうちどれ？
　→東京大神宮
・今まで新婦が一番嬉しかった新郎の言葉はどれ？
　→今日は20時に帰ります。
・新郎の得意なモノマネはなんでしょう？
  (実際に新郎にやってもらう)
　→ない
