### ISSUE TITLE
新郎がやっておくべきタスク一覧

### ISSUE THREAD

**Issue by shinmura326** [mantaroh/okamura#14]
期限１０月１０日の打ち合わせまで
- [x] 入場ムービーの写真データ（githhubにzipで固めてコミット）
- [x] 景品をお任せにするか、用意するか？
- [x] プチギフトの有無
- [x] 入場曲、退場曲のリクエスト
- [x] 新婦の住所確認（ライングループで共有）
- [x] 仲良くやっていくための約束（新郎分）と新婦へのメッセージ（これは当日まででOK）

**Comment by okamuran** [comment]
ラインのノートで連絡済み

**Comment by okamuran** [comment]
入場ムービーの写真データ
・子供のころの写真　20枚
・参加者と一緒に写っている写真　20枚
・２人の写真　20枚

**Comment by okamuran** [comment]
プチギフトなしのOKです。

**Comment by okamuran** [comment]
景品はおまかせ

**Comment by okamuran** [comment]
退場曲：マイアヒラサワ　Boom
入場曲：検討中

**Comment by shinmura326** [comment]
写真は直接もらったの一旦よしとする。

**Comment by shinmura326** [comment]
仲良くやっていくための約束（新郎分）と新婦へのメッセージ（これは当日まででOK）
は別途issue化する

**Comment by shinmura326** [comment]
入場曲
Carly Rae Jepsen - I Really Like You
