### ISSUE TITLE
クイズの素材を集めたい

### ISSUE THREAD

**Issue by shinmura326** [mantaroh/okamura#19]
クイズをリッチな見た目にするために画像とSEを集める必要がある。

欲しいもの
・問題５問分の背景画像。うち2つは新郎新婦の故郷にちなんだもの
・景品の画像。５種類の景品にそれぞれサンプル画像が必要。何があるかはdoc内のテキストで共有
・SE 音声。問題を読む前に流れるやつ(じゃ～じゃん)
・正解、不正解
・景品紹介時の音
・開始終了のイントロっぽい音楽

**Comment by mantaroh** [comment]
景品の画像 => https://github.com/mantaroh/okamura/blob/master/doc/picture/premium/how.txt

**Comment by shinmura326** [comment]
大丈夫っぽい
問題待機中のカチカチ音がないが、まあ許せる
