### ISSUE TITLE
問題表示から回答者選択を経由せずに正解不正解を表示したい

### ISSUE THREAD

**Issue by shinmura326** [mantaroh/okamura#21]
ゲームの進行上、問題表示→回答者選択→問題を再表示→正解、不正解（不正解なら問題表示からやり直し）となるのが望ましい。今の状態だと回答者選択→問題を再表示の後に回答者選択画面を経由しないといけないので、違和感がある。なので問題表示画面でも正解、不正解を出せるようにしたい。

**Comment by mantaroh** [comment]
I steal it.

**Comment by mantaroh** [comment]
modified each question screen flow as follow.
1) question title
2) question
3) choice of answer guys.
4) question
5) (if correct answered) correct page.
6) (if not correct answered) incorrect page

**Comment by mantaroh** [comment]
modified it.
https://github.com/mantaroh/mantaroh.github.io/commit/a3360c9994b016a92a731e816ea543ebab8a024c
