### ISSUE TITLE
正解結果表示と景品表示を別画面でやりたい

### ISSUE THREAD

**Issue by shinmura326** [mantaroh/okamura#22]
正解が決まった喜びと、景品が何かを期待するワクワク感を段階的に味わって欲しいので、同時に出さずに画面遷移を挟みたい。

**Comment by mantaroh** [comment]
I steal it.

**Comment by mantaroh** [comment]
modified adding to premium page.

https://github.com/mantaroh/mantaroh.github.io/commit/46fcac4dbf650a5ca12e8b7dbdf4aaf13590900c
