### ISSUE TITLE
新婚さんクイズ

### ISSUE THREAD

**Issue by shinmura326** [mantaroh/okamura#3]
新婚さんお二人の問題を作成、出題するクイズページ
前提条件
- [x] #9 が終了している
- [x] #10 が終了している
- クイズの問題を自動で画面に表示したい
- クイズの回答者を選択したい
- クイズ答えを表示したい
- クイズの景品を表示したい
- クイズの問題を司会のタイミングで次の問題に切り替えたい
↑------最低ライン------
- ４択の回答選択肢を作りたい
- 複数ある問題からランダムで問題を選んでほしい(一度出した問題は選ばれない。)
- クイズのSEがほしい
- 簡単に問題を登録する処理がほしい
- 一度出した問題は選ばれない。

**Comment by mantaroh** [comment]
I steal this issue.

**Comment by mantaroh** [comment]
effect sample is as follow:
  - flake http://liginc.co.jp/web/html-css/css/154338/2
  - bingo http://d.hatena.ne.jp/replication/touch/20101125/1290614615


draft background image :
 -  http://all-free-download.com/free-vector/wedding-card-background-images.html

**Comment by shinmura326** [comment]
答えは私が覚えておく必要があるけど大丈夫
