### ISSUE TITLE
アプリで使う言語、方式、管理方法を決めたい

### ISSUE THREAD

**Issue by shinmura326** [mantaroh/okamura#9]
アプリを作るための言語、やり方などを決めたい
難しい準備がいらない方法で作成、表示したい
- [x]  言語
- [ ]  画像などの素材の参照方法
- [ ]  データの管理方法
- [ ]  音声どうする？
- [x]  管理方法

**Comment by shinmura326** [comment]
データの置き方は検討中。
効果音の収集などしなければいけないので素材の一覧を考えないといけない

**Comment by shinmura326** [comment]
言語はChrome apps （Chrome上で動くアプリになる）
Yomen?でどうこうする的な話がよくわかっていない。

**Comment by mantaroh** [comment]
データ形式は、html データ。
あとは、問題数だけガシガシ作るー。

問題とかの指定方法は、↓参考
https://github.com/mantaroh/mantaroh.github.io/blob/master/okamura/main.js#L180

残課題は、作った html を Chrome App にパッケージングするとこ。
たぶん、マニフェストに制御ページ指定して、リソースとして HTML 置けば良い感じ
(パッケージングは手動。grunt とかやる時間が無い)

**Comment by shinmura326** [comment]
決めないことを決めたので終り
